import { Router } from 'express';
import { authMiddleware } from '../middlewares/auth.middleware';
import {
  listVendors,
  createVendor,
  listPurchaseRequests,
  approvePurchaseRequest,
  rejectPurchaseRequest,
  listPurchaseOrders,
  createGRN,
} from '../controllers/purchase.controller';

const router = Router();
router.use(authMiddleware);

// Vendors
router.get('/vendors', listVendors);
router.post('/vendors', createVendor);

// Purchase Requests (generated by Kitchen Manager from production plans)
router.get('/requests', listPurchaseRequests);
router.post('/requests/:id/approve', approvePurchaseRequest);
router.post('/requests/:id/reject', rejectPurchaseRequest);

// Purchase Orders
router.get('/orders', listPurchaseOrders);

// Goods Received Note — adds inventory batches and inward stock transactions
router.post('/orders/:id/grn', createGRN);

export default router;
