import { Router } from 'express';
import { authMiddleware } from '../middlewares/auth.middleware';
import { requirePermission } from '../middlewares/rbac.middleware';
import {
  listVendors,
  createVendor,
  listPurchaseRequests,
  approvePurchaseRequest,
  rejectPurchaseRequest,
  listPurchaseOrders,
  createGRN,
} from '../controllers/purchase.controller';

const router = Router();
router.use(authMiddleware);

// Vendors
router.get('/vendors', requirePermission('vendor_purchase_mgmt', 'view'), listVendors);
router.post('/vendors', requirePermission('vendor_purchase_mgmt', 'create'), createVendor);

// Purchase Requests (generated by Kitchen Manager from production plans)
router.get('/requests', requirePermission('vendor_purchase_mgmt', 'view'), listPurchaseRequests);
router.post('/requests/:id/approve', requirePermission('vendor_purchase_mgmt', 'approve'), approvePurchaseRequest);
router.post('/requests/:id/reject', requirePermission('vendor_purchase_mgmt', 'edit'), rejectPurchaseRequest);

// Purchase Orders
router.get('/orders', requirePermission('vendor_purchase_mgmt', 'view'), listPurchaseOrders);

// Goods Received Note — adds inventory batches and inward stock transactions
router.post('/orders/:id/grn', requirePermission('vendor_purchase_mgmt', 'approve'), createGRN);

export default router;
